/*
 * LIBRERIA CHE CONTIENE LE FUNZIONI USATE PER LA COMPARAZIONE TRA VARI RECORD
 */

#ifndef PROGETTO_LRNDNL_COMPARAZIONERECORD_H
#define PROGETTO_LRNDNL_COMPARAZIONERECORD_H

#include "recordSoggetto.h"

void confrontaRecord(RecordSoggetto *puntatore1, RecordSoggetto *puntatore2);

#endif //PROGETTO_LRNDNL_COMPARAZIONERECORD_H
